name: Internal Testing Deployment workflow

on:
  push:
    branches: [qa]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  distribute:
    name: Deploy app to internal testing track on play console
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}

      - name: Assemble Release bundle
        run: ./gradlew bundleRelease

      - name: Sign release bundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}

      - name: Setup Authorization with Google play store
        run: echo '${{secrets.SERVICE_ACCOUNT}}' > service_account.json

      - name: Deploy bundle to play console
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: com.mobile.xplore_nu
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: 'internal'
          whatsNewDirectory: whatsnew/