name: Unit Testing workflow

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL_VALUE: ${{ secrets.BASE_URL }}
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Create local.properties
        run: |
          echo "Creating local.properties file with BASE_URL from secret..."
          echo "BASE_URL=${{ secrets.BASE_URL }}" > local.properties
          echo "API_KEY=${{ secrets.API_KEY }}" > local.properties
          echo "MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}" > local.properties
          echo "MAPBOX_BASE_URL=${{ secrets.MAPBOX_BASE_URL }}" > local.properties
          echo "MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}" > local.properties
          echo "local.properties created with BASE_URL:"
          cat local.properties

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test --configuration-cache
